.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,18 +20,19 @@ jobs:
         include:
           - target: aarch64-unknown-linux-gnu
             runner_os: ubuntu-latest
+            command: both
           - target: aarch64-apple-darwin
             runner_os: macOS-latest
+            command: build
           - target: x86_64-unknown-linux-gnu
             runner_os: ubuntu-latest
+            command: both
           - target: x86_64-apple-darwin
             runner_os: macos-latest
-          - target: x86_64-pc-windows-msvc
-            runner_os: windows-latest
+            command: both
           - target: i686-unknown-linux-gnu
             runner_os: ubuntu-latest
-          - target: i686-pc-windows-msvc
-            runner_os: windows-latest
+            command: both
 
     steps:
       - name: Checkout repository
@@ -40,11 +41,22 @@ jobs:
       - name: Build artifact
         uses: houseabsolute/actions-rust-cross@v0
         with:
-          command: build
+          command: ${{ matrix.command }}
           target: ${{ matrix.target }}
           toolchain: stable
           args: --locked --release
           strip: true
+
+      - name: Package
+        run: |
+          RELEASE_DIR="target/${{ matrix.target }}/release"
+
+          if [ ! -d "$RELEASE_DIR" ]; then
+            echo "error: release directory not found: $RELEASE_DIR"
+            exit 1
+          fi
+
+          tar czvf workbench-0.1.0-${{ matrix.target }}.tar.gz $RELEASE_DIR/wb LICENSE.txt
 
       # - name: Create a release in GitHub
       #   uses: softprops/action-gh-release@v2
